<?php

declare(strict_types=1);

namespace Gcob\LaraSpecFirst\Generation;

/**
 * One file the build intends to write, held in memory before anything is written.
 *
 * The path is relative to the generated root and never absolute, which is what
 * lets {@see GeneratedTree} be the only place that knows where that root is —
 * and therefore the only place that has to prove nothing escapes it.
 */
final readonly class GeneratedFile
{
    /**
     * Every generated file carries this, and it is load-bearing rather than
     * decoration: it is how the build recognizes its own output when deciding
     * what to prune, so a file a human wrote inside the generated tree is never
     * deleted by us.
     */
    public const string MARKER = '@generated by lara-spec-first';

    public function __construct(
        public string $relativePath,
        public string $contents,
    ) {}
}
