<?php

declare(strict_types=1);

use Gcob\LaraSpecFirst\Generation\GeneratedFile;
use Gcob\LaraSpecFirst\Http\Controllers\SpecController;
use Gcob\LaraSpecFirst\Routing\GeneratedRoutesLocator;
use Illuminate\Contracts\Console\Kernel;
use Illuminate\Contracts\Http\Kernel as HttpKernel;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;
use Symfony\Component\Console\Output\BufferedOutput;

/*
 * The generated tree goes to a temporary directory, and the namespaces written
 * into it are served by one autoloader registered for the whole file.
 *
 * That autoloader is doing what Composer does in a real application: PSR-4 maps
 * `App\Http\Generated\` to `app/Http/Generated/` there, and nothing here can rely
 * on that because the tree is not in this package's autoload map. A few lines of
 * `spl_autoload_register` buy the same thing without writing generated PHP into
 * the repository, which would then need a `.gitignore` entry of its own and would
 * survive an interrupted run.
 *
 * The namespace itself is fresh per test rather than fixed for the file, for the
 * reason {@see buildNamespace()} gives: a class this process has declared once
 * cannot be reloaded, so a fixed namespace would let one test's generated bytes
 * answer another test's assertions.
 */

/**
 * One temporary tree for this file, computed once.
 *
 * A function with a static rather than a property on the test case: Pest closures
 * are bound to the test instance at runtime but typed as a pending call, so state
 * hung on `$this` is invisible to static analysis. A named function says the same
 * thing and can be checked.
 */
function buildTree(): string
{
    static $tree = null;

    return $tree ??= sys_get_temp_dir().'/lsf-build-'.bin2hex(random_bytes(6));
}

/**
 * A fresh generated namespace for each test, and the reason is PHP rather than
 * tidiness.
 *
 * `beforeEach` deletes and rebuilds the tree at the same paths, but a class this
 * process has already declared stays declared: PHP will not autoload a second
 * definition, and it tracks includes by path. So a fixed namespace would mean
 * every test after the first one to load a controller asserting against the bytes
 * *that* build wrote — silently, and correctly, for as long as every test builds
 * from the same fixture. A namespace nobody has loaded yet cannot be stale.
 *
 * Passing a value sets it; passing nothing reads it back.
 */
function buildNamespace(?string $fresh = null): string
{
    static $namespace = null;

    if ($fresh !== null) {
        $namespace = $fresh;
    }

    return $namespace ??= 'LsfBuild'.bin2hex(random_bytes(4));
}

beforeAll(function (): void {
    $tree = buildTree();

    // Registered on the root the per-test namespaces share, since the namespace
    // this maps from is not known yet when this runs. Everything after the first
    // separator is the path under the tree, which is the same rule Composer's
    // PSR-4 applies in a real application.
    spl_autoload_register(static function (string $class) use ($tree): void {
        if (! str_starts_with($class, 'LsfBuild')) {
            return;
        }

        $separator = strpos($class, '\\');

        if ($separator === false) {
            return;
        }

        $file = $tree.'/'.str_replace('\\', '/', substr($class, $separator + 1)).'.php';

        if (is_file($file)) {
            require $file;
        }
    });
});

beforeEach(function (): void {
    // Each test starts from an empty tree, so what one of them wrote can never
    // be what another one asserts.
    exec('rm -rf '.escapeshellarg(buildTree()));

    config()->set(GeneratedRoutesLocator::SETTING, buildTree());
    config()->set('lara-spec-first.generated.namespace', buildNamespace('LsfBuild'.bin2hex(random_bytes(4))));
    config()->set('lara-spec-first.spec.path', specFixturePath('operations.yaml'));
});

afterAll(function (): void {
    exec('rm -rf '.escapeshellarg(buildTree()));
});

function build(): int
{
    return app(Kernel::class)->call('spec:build');
}

/**
 * @return list<string> every path under the generated tree, relative to it
 */
function treeContents(string $root): array
{
    if (! is_dir($root)) {
        return [];
    }

    $found = [];

    /** @var iterable<SplFileInfo> $entries */
    $entries = new RecursiveIteratorIterator(
        new RecursiveDirectoryIterator($root, RecursiveDirectoryIterator::SKIP_DOTS),
    );

    foreach ($entries as $entry) {
        // Normalized to `/` rather than left as the platform's separator, because
        // every caller compares against a path the generator writes — and the
        // generator writes `Controllers/` on every platform.
        $found[] = str_replace(DIRECTORY_SEPARATOR, '/', substr($entry->getPathname(), strlen($root) + 1));
    }

    sort($found);

    return $found;
}

it('emits one controller per operation and the routes file', function (): void {
    expect(build())->toBe(0)
        ->and(treeContents(buildTree()))->toBe([
            'Controllers/CreatePostController.php',
            'Controllers/DeleteUsersIdController.php',
            'Controllers/ShowCurrentUserController.php',
            'Controllers/ShowUserController.php',
            GeneratedRoutesLocator::FILE,
        ]);
});

// The fixture declares `delete /users/{id}` without an `operationId`, which is
// what makes it worth building against: the derived name and the declared one
// have to come out of the same run.
it('names a controller from the operationId, or from the method and path', function (): void {
    build();

    expect(is_file(buildTree().'/Controllers/ShowUserController.php'))->toBeTrue()
        ->and(is_file(buildTree().'/Controllers/DeleteUsersIdController.php'))->toBeTrue();
});

/*
 * The adversarial half. `hostile-paths.yaml` is entirely valid OpenAPI and
 * entirely hostile to a generator that builds PHP by concatenating strings: a
 * document is data, a generated file is code, and the boundary between them is
 * where injection lives.
 *
 * The guard for this already existed — `emits PHP that parses` runs `php -l` over
 * everything emitted. What was missing was a fixture that attacks it. That is the
 * general lesson: a test only covers the inputs somebody thought to write down.
 */

function buildHostile(): int
{
    config()->set('lara-spec-first.spec.path', specFixturePath('hostile-paths.yaml'));

    return build();
}

it('emits PHP that parses from a contract written to break it', function (): void {
    expect(buildHostile())->toBe(0);

    foreach (treeContents(buildTree()) as $relative) {
        exec('php -l '.escapeshellarg(buildTree().'/'.$relative), $output, $status);

        expect($status)->toBe(0, $relative.' does not parse: '.implode("\n", $output));
    }
});

// Worse than a parse error, and the reason this fixture exists. A value closing a
// block comment ends the docblock early, turns what follows into a statement, and
// lets the docblock's own closing delimiter reopen and close a comment around the
// rest — so the file parses, loads, and runs whatever the document put there.
// Verified by side effect rather than by reading the output, because that is what
// an attacker would use.
it('executes nothing a contract smuggled into a docblock', function (): void {
    $witness = sys_get_temp_dir().'/lsf-injected';
    @unlink($witness);

    buildHostile();

    foreach (treeContents(buildTree()) as $relative) {
        if (str_ends_with($relative, '.php') && str_contains($relative, 'Controllers/')) {
            require buildTree().'/'.$relative;
        }
    }

    expect(is_file($witness))->toBeFalse('a generated file executed code from the specification');
});

it('routes a path a naive literal would have broken', function (): void {
    buildHostile();

    require buildTree().'/'.GeneratedRoutesLocator::FILE;

    $response = app(HttpKernel::class)->handle(Request::create("/users/o'brien"));

    expect($response->getStatusCode())->toBe(501);
});

it('emits PHP that parses', function (): void {
    build();

    foreach (treeContents(buildTree()) as $relative) {
        exec('php -l '.escapeshellarg(buildTree().'/'.$relative), $output, $status);

        expect($status)->toBe(0, $relative.' does not parse: '.implode("\n", $output));
    }
});

// Idempotence, as the validation asks for it: running it twice in a row changes
// nothing the second time.
it('changes nothing on a second run against an unchanged specification', function (): void {
    build();

    $before = [];

    foreach (treeContents(buildTree()) as $relative) {
        $before[$relative] = [
            file_get_contents(buildTree().'/'.$relative),
            filemtime(buildTree().'/'.$relative),
        ];
    }

    build();

    $after = [];

    foreach (treeContents(buildTree()) as $relative) {
        $after[$relative] = [
            file_get_contents(buildTree().'/'.$relative),
            filemtime(buildTree().'/'.$relative),
        ];
    }

    expect($after)->toBe($before);
});

// The flag is part of the command's signature, which is public API surface the
// moment the package ships — and it is the only way to point the build at a
// document other than the configured one.
it('reads the specification a flag names instead of the configured one', function (): void {
    config()->set('lara-spec-first.spec.path', specFixturePath('does-not-exist.yaml'));

    $exit = app(Kernel::class)->call('spec:build', ['--spec' => specFixturePath('operations.yaml')]);

    expect($exit)->toBe(0)
        ->and(treeContents(buildTree()))->toContain('Controllers/ShowUserController.php');
});

// `changedNothing()` is what makes idempotence legible from the outside, so the
// command says it in words rather than leaving a reader to notice that every
// count came back zero.
it('says it changed nothing when a second run changes nothing', function (): void {
    build();

    $output = new BufferedOutput;
    app(Kernel::class)->call('spec:build', [], $output);

    expect($output->fetch())->toContain('Already up to date.');
});

// The invariant, checked where a consumer would feel it: the build owns its own
// directory and nothing else, so a file beside the tree is untouched.
it('writes nothing outside the tree it owns', function (): void {
    $neighbour = dirname(buildTree()).'/lsf-neighbour-'.bin2hex(random_bytes(4));
    mkdir($neighbour, 0o777, true);
    file_put_contents($neighbour.'/untouched.php', 'kept');

    try {
        build();

        expect(scandir($neighbour))->toBe(['.', '..', 'untouched.php'])
            ->and(file_get_contents($neighbour.'/untouched.php'))->toBe('kept');
    } finally {
        exec('rm -rf '.escapeshellarg($neighbour));
    }
});

// The property that keeps idempotence true in a real project rather than only in
// a test. Almost every Laravel application formats its code, and `phpdoc_separation`
// ships in both Pint's Laravel preset and php-cs-fixer's defaults — so output that
// is not already canonical under it would be rewritten by the consumer's formatter
// and rewritten back by the next build, forever. Emitting the canonical form is
// what stops the two from fighting.
it('emits output a formatter finds nothing to change in', function (): void {
    build();

    exec(
        'vendor/bin/pint --test '.escapeshellarg(buildTree()).' 2>&1',
        $output,
        $status,
    );

    expect($status)->toBe(0, "Pint would rewrite generated output:\n".implode("\n", $output));
});

// Every file, rather than a sample of one. The norm is emitted unconditionally,
// so the assertion that matches it is one that fails the moment a new kind of
// generated file arrives without it — which is exactly how a convention that
// lives in prose erodes. What each part has to say is asserted at the emitters,
// in tests/Unit/Generation/; what is proven here is that the real command puts it
// in everything it writes.
// A 3.1 document may legally carry only `webhooks`, and zero routes is an outcome
// rather than an error. The file is still written — it is what replaces the routes
// a previous build registered — and it is held to the same promise as any other
// generated file: a formatter finds nothing to change in it. It used to fail that,
// on `single_line_after_imports` and `single_blank_line_at_eof`, over an empty
// registration block nobody could see.
it('writes a routes file a formatter accepts when the contract routes nothing', function (): void {
    config()->set('lara-spec-first.spec.path', specFixturePath('openapi-3.1-webhooks-only.yaml'));

    expect(build())->toBe(0)
        ->and(treeContents(buildTree()))->toBe([GeneratedRoutesLocator::FILE]);

    exec('vendor/bin/pint --test '.escapeshellarg(buildTree()).' 2>&1', $output, $status);

    $contents = (string) file_get_contents(buildTree().'/'.GeneratedRoutesLocator::FILE);

    expect($status)->toBe(0, "Pint would rewrite generated output:\n".implode("\n", $output))
        ->and($contents)->toContain('No operation, so this file registers none')
        ->and($contents)->not->toContain('Every controller imported below');
});

// And it still boots: the provider loads the file, and an application with no
// generated route is not an application that fails to start.
it('registers no route from a contract that routes nothing', function (): void {
    config()->set('lara-spec-first.spec.path', specFixturePath('openapi-3.1-webhooks-only.yaml'));
    build();

    require buildTree().'/'.GeneratedRoutesLocator::FILE;

    $generated = array_filter(
        app('router')->getRoutes()->getRoutes(),
        static fn (Route $route): bool => str_contains($route->getActionName(), 'routeAction'),
    );

    expect($generated)->toBe([]);
});

it('carries provenance, findings and navigation into every file it writes', function (): void {
    build();

    $files = treeContents(buildTree());
    $missing = [];

    foreach ($files as $relative) {
        $contents = (string) file_get_contents(buildTree().'/'.$relative);

        foreach ([GeneratedFile::MARKER, 'Provenance', 'Findings', 'Navigation'] as $part) {
            if (! str_contains($contents, $part)) {
                $missing[] = $relative.' carries no '.$part;
            }
        }
    }

    expect($files)->not->toBeEmpty()
        ->and($missing)->toBe([]);
});

// The pointer is what rename detection will compare, so every controller carries
// one rather than most of them.
it('carries the position it came from in every controller it writes', function (): void {
    build();

    $withoutPointer = array_values(array_filter(
        treeContents(buildTree()),
        static fn (string $relative): bool => str_starts_with($relative, 'Controllers/')
            && ! str_contains((string) file_get_contents(buildTree().'/'.$relative), '#/paths/'),
    ));

    expect($withoutPointer)->toBe([])
        ->and(file_get_contents(buildTree().'/Controllers/ShowUserController.php'))
        ->toContain('#/paths/~1users~1{id}/get');
});

// Named from the project root, and asserted as the absence of the alternative.
// A generated file may be committed — that is the consumer's `.gitignore` choice,
// not ours — and an absolute path in a repository differs between every developer
// and every CI runner, which is a diff nobody made and one machine's directory
// layout published.
it('names its source from the project root rather than absolutely', function (): void {
    build();

    $absolute = [];

    foreach (treeContents(buildTree()) as $relative) {
        $contents = (string) file_get_contents(buildTree().'/'.$relative);

        if (! str_contains($contents, 'tests/Fixtures/operations.yaml')) {
            $absolute[] = $relative.' does not name the specification';
        }

        if (str_contains($contents, dirname(__DIR__, 3))) {
            $absolute[] = $relative.' names it absolutely';
        }
    }

    expect($absolute)->toBe([]);
});

// The two-class seam, asserted on the classes rather than on the text that
// produced them: `final` for as long as nothing may extend a generated
// controller, one shipped base for every operation, and one declared method so
// the routes file can name it as a plain string.
//
// DECISION: the emitter's own tests assert these three properties on the emitted
// text, and this test asserts them again on what PHP loaded. The overlap is
// deliberate rather than an oversight — the failure modes differ. Text that reads
// `final class` and a class PHP reports as final are the same claim only while
// nothing between them is wrong: the planner could route to a class the emitter
// never wrote, and a `use` this file resolves differently would change the parent
// without changing a byte of the emitter's output. Do not delete either copy as a
// duplicate.
// The fixture this file builds from declares no `x-controller`, which is what makes
// `final` the expected answer for every class in it. The other branch is asserted
// above, from a fixture that declares one.
it('generates a final controller over the shipped base, carrying one routeAction', function (): void {
    build();

    $controllers = array_values(array_filter(
        treeContents(buildTree()),
        static fn (string $relative): bool => str_starts_with($relative, 'Controllers/'),
    ));

    $expected = array_map(
        static fn (string $relative): string => buildNamespace().'\\Controllers\\'.basename($relative, '.php'),
        $controllers,
    );

    // Loaded through the registered autoloader, the way an application reaches
    // them, rather than by requiring the files: what is under test includes the
    // class landing where its namespace says it does.
    foreach ($expected as $class) {
        expect(class_exists($class))->toBeTrue($class.' does not autoload');
    }

    // Reached through what PHP has actually loaded rather than by naming a class
    // from a filename: this is the same list, and it is a list of loaded classes
    // rather than of strings that look like ones.
    $loaded = array_values(array_intersect(get_declared_classes(), $expected));

    expect($expected)->not->toBeEmpty()
        ->and($loaded)->toHaveCount(count($expected));

    foreach ($loaded as $class) {
        $reflection = new ReflectionClass($class);
        $parent = $reflection->getParentClass();
        $declared = array_map(
            static fn (ReflectionMethod $method): string => $method->getName(),
            array_filter(
                $reflection->getMethods(),
                static fn (ReflectionMethod $method): bool => $method->getDeclaringClass()->getName() === $class,
            ),
        );

        expect($reflection->isFinal())->toBeTrue($class.' is not final')
            ->and($parent === false ? null : $parent->getName())->toBe(SpecController::class)
            ->and(array_values($declared))->toBe(['routeAction']);
    }
});

/*
 * The two-class seam, through the real command. What a unit test cannot say here is
 * that the pieces agree: the class the emitter writes, the target the routes file
 * registers, and the answer the autoloader gave about the child are three
 * decisions taken in three classes from one fact.
 *
 * The fixture's first operation names a class this repository really autoloads and
 * its second names one nothing has written, so both branches come out of one run.
 */

function buildCustomControllers(): int
{
    config()->set('lara-spec-first.spec.path', specFixturePath('custom-controllers.yaml'));

    return build();
}

it('generates a parent nothing forbids extending when the contract names a controller', function (): void {
    expect(buildCustomControllers())->toBe(0);

    $parent = (string) file_get_contents(buildTree().'/Controllers/WrittenController.php');

    expect($parent)->toContain('class WrittenController extends SpecController')
        ->and($parent)->not->toContain('final class');
});

// And the operation that declares nothing is still `final` in the same run, which
// is the half a single-operation fixture could not show.
it('keeps a controller final in the same run when nothing declares it', function (): void {
    buildCustomControllers();

    expect(file_get_contents(buildTree().'/Controllers/HealthController.php'))
        ->toContain('final class HealthController extends SpecController');
});

it('routes to the custom controller when it exists, and to the parent when it does not', function (): void {
    buildCustomControllers();

    $routes = (string) file_get_contents(buildTree().'/'.GeneratedRoutesLocator::FILE);

    expect($routes)
        ->toContain('use Gcob\\LaraSpecFirst\\Tests\\Fixtures\\CustomControllers\\WrittenController;')
        ->toContain('use '.buildNamespace().'\\Controllers\\NotWrittenYetController;')
        ->toContain("Route::get('/users/{id}', [WrittenController::class, 'routeAction']);")
        ->toContain("Route::get('/posts', [NotWrittenYetController::class, 'routeAction']);");
});

// The note above the imports has to stay true of what is actually in the block:
// running a build would not create a class the developer owns, so telling them to
// rebuild in order to restore one would send them the wrong way.
it('tells a reader which imports a build could restore and which it could not', function (): void {
    buildCustomControllers();

    $routes = (string) file_get_contents(buildTree().'/'.GeneratedRoutesLocator::FILE);

    expect($routes)
        ->toContain('of two kinds')
        ->toContain('A custom one missing means the class `x-controller` names does not')
        ->and($routes)->not->toContain('Every controller imported below is generated');
});

// The count the command reports has to exclude what the project's own controller
// answers. Warning about it would tell a developer their controller does not count.
it('counts an operation its custom controller answers as implemented', function (): void {
    config()->set('lara-spec-first.spec.path', specFixturePath('custom-controllers.yaml'));

    $output = new BufferedOutput;

    expect(app(Kernel::class)->call('spec:build', [], $output))->toBe(0);

    expect($output->fetch())->toContain('2 of 3 operation(s) have no implementation');
});

it('still emits PHP that parses for both halves of the seam', function (): void {
    buildCustomControllers();

    foreach (treeContents(buildTree()) as $relative) {
        exec('php -l '.escapeshellarg(buildTree().'/'.$relative), $output, $status);

        expect($status)->toBe(0, $relative.' does not parse: '.implode("\n", $output));
    }

    exec('vendor/bin/pint --test '.escapeshellarg(buildTree()).' 2>&1', $pint, $pintStatus);

    expect($pintStatus)->toBe(0, "Pint would rewrite generated output:\n".implode("\n", $pint));
});

// The whole point of the build, end to end: a contract becomes a route that
// answers. 501 rather than 404, because the specification says the endpoint is
// there and nothing should contradict it at the wire.
// The parameterized case matters on its own: Laravel hands route parameters to
// the action by reflection, and a generated `routeAction()` that declares none
// has to survive being handed one.
it('produces routes that answer 501 until something implements them', function (
    string $method,
    string $uri,
): void {
    build();

    require buildTree().'/'.GeneratedRoutesLocator::FILE;

    $response = app(HttpKernel::class)->handle(Request::create($uri, $method));

    expect($response->getStatusCode())->toBe(501);
})->with([
    'literal path' => ['GET', '/users/me'],
    'templated path' => ['GET', '/users/42'],
    'a verb that is not GET' => ['POST', '/posts'],
    'a second verb on one path' => ['DELETE', '/users/42'],
]);

it('registers the routes in the order the document writes them', function (): void {
    build();

    require buildTree().'/'.GeneratedRoutesLocator::FILE;

    $uris = array_values(array_map(
        static fn (Route $route): string => $route->uri(),
        array_filter(
            app('router')->getRoutes()->getRoutes(),
            static fn (Route $route): bool => str_contains($route->getActionName(), 'Controller@routeAction'),
        ),
    ));

    expect($uris)->toBe(['users/me', 'users/{id}', 'users/{id}', 'posts']);
});

/*
 * A refusal is a diagnostic, not a stack trace. Every exception this package
 * raises implements `SpecException`, and the messages are written to be read —
 * they name the construct, the position and the fix. Rendering one as an uncaught
 * exception with a source excerpt throws that away, in the command that is meant
 * to be the contract's `nginx -t`.
 */
it('reports a document it refuses instead of throwing at the reader', function (
    string $fixture,
    string $expected,
): void {
    config()->set('lara-spec-first.spec.path', specFixturePath($fixture));

    $output = new BufferedOutput;

    expect(app(Kernel::class)->call('spec:build', [], $output))->toBe(1)
        ->and($output->fetch())->toContain($expected)
        ->and(treeContents(buildTree()))->toBe([]);
})->with([
    'no paths at 3.0' => ['openapi-3.0-no-paths.yaml', 'must declare "paths"'],
    'not valid YAML' => ['malformed.yaml', 'not valid YAML or JSON'],
    'not a mapping' => ['not-a-mapping.yaml', 'not-a-mapping.yaml'],
    'a version we do not implement' => ['swagger-2.0.yaml', '2.0'],
    'a reference cycle' => ['cycle-pointer.yaml', 'closes a cycle'],
]);

it('fails without writing anything when there is no specification', function (): void {
    config()->set('lara-spec-first.spec.path', specFixturePath('does-not-exist.yaml'));

    expect(build())->toBe(1)
        ->and(treeContents(buildTree()))->toBe([]);
});

// Through the real command, because the refusal has to arrive as a diagnostic
// rather than as a file that will not parse. `{2fa}` is a legal route parameter
// and `$2fa` is not a variable, so the generated `routeAction` could not declare
// it — and the whole tree stays untouched, which is the property planning before
// writing exists for.
it('refuses a path parameter the generated method could not declare', function (): void {
    config()->set('lara-spec-first.spec.path', specFixturePath('unusable-path-parameter.yaml'));

    $output = new BufferedOutput;

    expect(app(Kernel::class)->call('spec:build', [], $output))->toBe(1)
        ->and($output->fetch())->toContain('cannot be a PHP variable')
        ->and(treeContents(buildTree()))->toBe([]);
});
